# Generated by Django 5.1.3 on 2024-12-09 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('tipo', models.TextField()),
                ('capacidade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Frasco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capacidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('custo_por_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('unidade_medida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('cliente', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulacao.materiaprima')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='manipulacao.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_itens', to='manipulacao.formula')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulacao.materiaprima')),
                ('Orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_itens', to='manipulacao.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.CharField(max_length=255)),
                ('ultima_atualizacao', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_recebida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulacao.materiaprima')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='manipulacao.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='TextoRotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('nome', models.TextField()),
                ('frasco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos_rotulo', to='manipulacao.frasco')),
            ],
        ),
    ]
