# Generated by Django 5.1.3 on 2024-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_rename_column_kanbancolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MÉDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIUM', max_length=6),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('A Fazer', 'A Fazer'), ('Em Progresso', 'Em Progresso'), ('Feito', 'Feito')], max_length=50),
        ),
    ]
