# Generated by Django 5.1.3 on 2024-12-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_card_priority_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=6),
        ),
    ]
