# Generated by Django 5.1.3 on 2024-12-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=10)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('porte', models.CharField(blank=True, max_length=50, null=True)),
                ('abertura', models.DateField(blank=True, null=True)),
                ('atividade_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('natureza_juridica', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_situacao', models.DateField(blank=True, null=True)),
                ('motivo_situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao_especial', models.CharField(blank=True, max_length=255, null=True)),
                ('data_situacao_especial', models.DateField(blank=True, null=True)),
                ('capital_social', models.CharField(blank=True, max_length=50, null=True)),
                ('simples_optante', models.BooleanField(default=False)),
                ('simei_optante', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
