# Generated by Django 5.1.3 on 2024-12-12 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_dinheiro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_convenio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitarAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('sangria', 'Sangria'), ('pausa', 'Pausa'), ('fechamento', 'Fechamento')], max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='frente_de_caixa.caixa')),
            ],
        ),
    ]
