# Generated by Django 5.1.3 on 2024-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome_farmacia', models.CharField(max_length=100)),
                ('responsavel_tecnico', models.CharField(max_length=100)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('perda', 'Perda')], max_length=20)),
                ('medicamento', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimentacao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSNGPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('status_envio', models.CharField(default='Pendente', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
