# Generated by Django 5.1.3 on 2024-12-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emissor', models.CharField(max_length=14)),
                ('cpf_transmissor', models.CharField(max_length=11)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_terapeutica', models.IntegerField(choices=[(1, 'Antimicrobiano'), (2, 'Sujeito a controle especial')])),
                ('registro_ms', models.CharField(max_length=13)),
                ('numero_lote', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('unidade_medida', models.IntegerField(choices=[(1, 'Caixas'), (2, 'Frascos')])),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='sngpc.inventario')),
            ],
        ),
    ]
