# Generated by Django 5.1.3 on 2024-12-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngpc', '0002_inventario_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('registro_ms', models.CharField(max_length=20)),
                ('lote', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EstablishmentConfig',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='inventario',
        ),
        migrations.DeleteModel(
            name='MedicamentoMovimentacao',
        ),
        migrations.DeleteModel(
            name='RegistroSNGPC',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
