# Generated by Django 5.1.3 on 2024-12-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngpc', '0004_configuracaosngpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='xmls/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
