# Generated by Django 5.1.3 on 2024-12-10 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_interno', models.CharField(max_length=100, unique=True)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_fisica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inventario', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.produto')),
            ],
        ),
    ]
