# Generated by Django 5.1.3 on 2024-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoContabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('emissao_nfe', 'Emissão NF-e'), ('emissao_nfse', 'Emissão NFS-e'), ('sat', 'SAT')], max_length=50)),
                ('data_geracao', models.DateField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('corrente', 'Corrente'), ('poupança', 'Poupança')], default='corrente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='pendente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebida', 'Recebida')], default='pendente', max_length=50)),
            ],
        ),
    ]
