# Generated by Django 5.1.3 on 2024-12-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF')], max_length=4)),
                ('numero_documento', models.CharField(max_length=18)),
                ('valor_credito_limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_pagamento', models.DateField()),
                ('tipos_pagamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cobranca', models.DateField()),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_cobranca', models.CharField(max_length=20)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_convenio', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(max_length=20)),
                ('percentual_pago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado'), ('bloqueado', 'Bloqueado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente')),
            ],
        ),
    ]
